apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myshuttle-web"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myshuttle-web
  template:
    metadata:
      labels:
        app: myshuttle-web
    spec:
      containers:
        - name: "myshuttle-web"
          image: "aksrepo2505.azurecr.io/myshuttle-web"
          ports:
          - containerPort: 8080
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myshuttle-db"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myshuttle-db
  template:
    metadata:
      labels:
        app: myshuttle-db
    spec:
      containers:
        - name: "myshuttle-db"
          image: "aksrepo2505.azurecr.io/myshuttle-db"
          ports:
          - containerPort: 3306
