apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myshuttle"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myshuttle
  template:
    metadata:
      labels:
        app: myshuttle
    spec:
      containers:
        - name: "myshuttle-web"
          image: "aksrepo2505.azurecr.io/myshuttle-web"
          ports:
          - containerPort: 80
        - name: "myshuttle-db"
          image: "aksrepo2505.azurecr.io/myshuttle-db"
          ports:
          - containerPort: 3306
