apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "aksnew2505-9c39"
    labels:
        app: "aksnew2505-9c39"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: aksnew2505f72e-aksnew2505-9c39.67cd52e6d6894d30bb14.eastus2.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "aksnew2505-9c39"
                servicePort: 80