  
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: "aksnew2505-9c39"
    labels:
        app: "aksnew2505-9c39"
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: "aksnew2505-9c39"
    servicePort: 80
    
