  
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: "myshuttle"
    labels:
        app: "myshuttle"
    annotations:
        kubernetes.io/ingress.class: nginx
spec:
  rules:
    http:
      paths:
        path: /myshuttle
        - backend:
            serviceName: "myshuttle-web"
            servicePort: 80

    
