  
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: "aksnew2505-9c39"
    labels:
        app: "aksnew2505-9c39"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: aksnew2505-9c39.cb37bf228e0b4cbd9386.eastus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: "aksnew2505-9c39"
          servicePort: 80
        path: /
    
