  
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: "myshuttle"
    labels:
        app: "myshuttle"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: myshuttle.cb37bf228e0b4cbd9386.eastus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: "myshuttle-web"
          servicePort: 8080
        path: /myshuttle
    
