apiVersion: v1
kind: Service
metadata:
    name: "aksnew2505-9c39"
    labels:
        app: "aksnew2505-9c39"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksnew2505-9c39"
