# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths: 
      [.github/workflows/main.yaml ]
#   branches: [ master ]
#   pull_request:
#   branches: [ master ]

# A workflow to build Myshuttle docker image
jobs:

     
  build:
    env: 
      wardir: '.'
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run:  mvn -Dmaven.test.skip=true -B package --file pom.xml

    
    - name: show the target directory
      run: |
        ls ./target
        echo "::set-env name=wardir::$GITHUB_WORKSPACE"

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: aksrepo2505.azurecr.io
        username: ${{ secrets.ACR_AKSREPO2505_USERNAME }}
        password: ${{ secrets.ACR_AKSREPO2505_PASSWORD }}
    
    - name: Build and push image to ACR
      id: build-image
    
      run: |
        echo "war directory:"${{ env.wardir }}
        ls ${{ env.wardir }}
        docker build . -f  "./src/Dockerfile" -t aksrepo2505.azurecr.io/myshuttle2:${{ github.sha }} 
        docker push aksrepo2505.azurecr.io/myshuttle2:${{ github.sha }}

# Deployment to Kubernetes

    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
        resource-group: 'AKSVNETRG'
        cluster-name: 'aksarc2505'
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myshuttle2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myshuttle2`
        fi
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myshuttle2
        container-registry-url: aksrepo2505.azurecr.io
        container-registry-username: ${{ secrets.acr_aksrepo2505_username }}
        container-registry-password: ${{ secrets.acr_aksrepo2505_password }}
        secret-name: aksrepo2505dockerauth       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: myshuttl2
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          aksrepo2505.azurecr.io/myshuttle2:${{ github.sha }}
        imagepullsecrets: |
          aksrepo2505dockerauth
